export const events = [
  {
    id: 1,
    image: '',
    eventTitle: '',
    eventDesc: '',
    eventDate: '',
    eventStatus: 'active',
    eventNumber: '8576575782',
    guests: 14,
  },
  {
    id: 2,
    image: '',
    eventTitle: '',
    eventDesc: '',
    eventDate: '',
    eventStatus: 'active',
    eventNumber: '8576575782',
    guests: 14,
  },
  {
    id: 3,
    image: '',
    eventTitle: '',
    eventDesc: '',
    eventDate: '',
    eventStatus: 'active',
    eventNumber: '8576575782',
    guests: 14,
  },
  {
    id: 4,
    image: '',
    eventTitle: '',
    eventDesc: '',
    eventDate: '',
    eventStatus: 'active',
    eventNumber: '8576575782',
    guests: 14,
  },
  {
    id: 5,
    image: '',
    eventTitle: '',
    eventDesc: '',
    eventDate: '',
    eventStatus: 'active',
    eventNumber: '8576575782',
    guests: 14,
  },
  {
    id: 6,
    image: '',
    eventTitle: '',
    eventDesc: '',
    eventDate: '',
    eventStatus: 'active',
    eventNumber: '8576575782',
    guests: 14,
  },
];